# role: ds_server_admin
# file: tasks/odbc.yml
# description: Set odbc drivers properties

---

# Add header for the connection
- name: update odbc file step1
  when: odbc is defined 
  #with_items: "{{ odbc }}"
  ini_file:
     path: "{{ DSHOME  }}/.odbc.ini"
     section: ODBC Data Sources
     backup: yes
     option: "{{ item.key }}"
     value: "{{ item.value.label }}"
     no_extra_spaces: yes
  loop: "{{ lookup('dict',odbc | default({}),wantlist=True) }}"


# Update configuration in odbc.ini  
- name: update odbc file step2
  when: odbc is defined
  register: odbc_status
  with_subelements:
      - "{{ lookup('dict',odbc | default({}),wantlist=True) }}"
      - "value.configuration"
  ini_file:
       path: "{{ DSHOME  }}/.odbc.ini"
       section: "{{ item.0.key }}"
       option: "{{ item.1.keys() | first }}"
       value: "{{ item.1.values() | first }}"
       #backup: yes
       no_extra_spaces: yes


# Restart engine (RESTART environnement variable must be set to TRUE)
- name: restart engine
  shell: "{{ item }}"
  with_items: "{{ restart.engine }}"
  when: odbc_status.changed and lookup('env','RESTART') == 'TRUE'   
