# file : project.yml
# description: example playbook for project administration

---
# these first variables are mandatory
# engine is defined in the inventory file but hosts could be hard coded or reference a variable
- hosts: engine
  remote_user: dsadm
  roles:
          - common
          - ds_project_admin

  vars:
        # project name
        project: dstage1
        permissions:
                users: 
                   developerUser:
                     role: Developer 
        # parallelism configuration
        nodes: 2
        apt_config_file: "{{ project }}.apt"
        # odbc connections
        odbc: [ postgres ]
        # project properties 
        # they are defined by labels (see configuration.properties in roles/ds_project_admin/defaults/main.yml)
        properties:
                Handle Failed Activities: true
                Log Warnings: true
                Log Report: false
                Supress Summary: false
                Generate Operational Metadata: false
                RCP For New Links: true
                OSH Visible: true
                Job Administration: true
                RCP: true
                Protected: false
                Advanced Runtime Options: 
                Purges:
                        #Days: 15
                        Runs: 5

        # project environnement variables
        ds_env:
                - name: example_var
                  value: "example_val"
                  prompt: "this is an example"
                - name: pg_password
                  value: "{{ db.postgres.password }}"
                  prompt: "database password"
                - name: pg_user
                  value: "{{ db.postgres.user }}"
                  prompt: "database user"
                - name: pg_host
                  value: "{{ db.postgres.host }}"
                  prompt: "database host"
                - name: APT_CONFIG_FILE
                  value: "{{ APT_CONFIG_FILE }}"

