---
- hosts: engine
  remote_user: dsadm
  tasks:
          - import_role:
                  name: project_admin
  vars:
        project: dstage3
        odbc: [ postgres ]
        properties:
                Add Checkpoints: true
                Handle Failed Activities: true
                Log Warnings: true
                Log Report: true
                Supress Summary: false
                Generate Operational Metadata: false
                Message Handler: 
                RCP For New Links: true
                OSH Visible: true
                Job Administration: true
                RCP: true
                Protected: false
                Advanced Runtime Options: 
                Purges:
                        #Days: 15
                        Runs: 5

        ds_env:
                - name: test
                  value: "{{ test }}"
        #          absent: true
        #          prompt: test
        #        - name: test2
        #          value: xxxtata
        #          prompt: test2
        #        - name: test3
        #          value: "{{ secrets.test.pass1 }}"
        #          encrypted: true
        #          prompt: test3
        #        - name: test4
        #          value: yyyyy
        #        - name: new
